# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :release do
    puts ENV['TRAVIS_PULL_REQUEST']
    increment_build_number
    swiftlint
    archive
    documentation
    if git_branch == 'master' && ENV['TRAVIS_PULL_REQUEST'] == 'false'
      changelog = changelog_from_git_commits(commits_count: 1)
      set_github_release(
          repository_name: 'leoMehlig/TDLib-iOS',
          name: changelog.lines.first,
          tag_name: "#{get_version_number}.#{get_build_number}",
          description: changelog.lines.drop(1).join(''),
          commitish: 'master',
          upload_assets: ['TDLib.framework.zip'],
          is_prerelease: true
      )
      sh('./push.sh')
    end
  end

  lane :archive do
    carthage(command: 'bootstrap', use_ssh: true, platform: 'iOS', use_binaries: true)
    carthage(command: 'build', no_skip_current: true, platform: 'iOS', cache_builds: true)
    carthage(command: 'archive', frameworks: ['TDLib'])
  end

  lane :documentation do
    jazzy
  end
end
