# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :release do
    if last_git_commit[:author] != 'ci-leomehlig' && git_branch == 'master'
      # begin
      #   # ENV['SOURCEKIT_LOGGING'] = 3
      #   # documentation
      # rescue
      #   puts 'jazzy failed. Whatever lets contiune'
      # end
      increment_build_number
      archive
      changelog = changelog_from_git_commits(commits_count: 1)
      set_github_release(
          repository_name: 'leoMehlig/TDLib-iOS',
          name: changelog.lines.first,
          tag_name: "#{get_version_number}.#{get_build_number}",
          description: changelog.lines.drop(1).join(""),
          commitish: 'master',
          upload_assets: ['TDLib.framework.zip']
      )
      git_commit(
        path: ["./docs/*", './TDLib/Info.plist', './TDLibTests/Info.plist', './TDLib.xcodeproj/project.pbxproj'], 
        message: "CI commit"
      )
      push_to_git_remote(tags: false)
    end
  end

  lane :archive do
    carthage(command: 'bootstrap', no_build: true, use_ssh: true)
    carthage(command: 'build', no_skip_current: true, verbose: true)
    carthage(command: 'archive', frameworks: ['TDLib'])
  end

  lane :documentation do
    jazzy
  end
end
